### ISSUE TITLE
jdiff not ble to catch reference key in dict of dicts

### ISSUE THREAD

**Issue by lvrfrc87** [networktocode/jdiff#91]
### Environment
* Python version:  3.7
* jdiff version:  0.0.2

### Expected Behavior
As it stands now, `jdiff` can catch a reference key only in a list of dictionary. There are case where NAPALM returns dict of dicts. In the example below, we want `.local.` and `.local..0`  to be the ref key of  `is_up`
```
{
  ".local.": {
    "description": "",
    "is_enabled": true,
    "is_up": true,
    "last_flapped": -1,
    "mac_address": "Unspecified",
    "mtu": 0,
    "speed": -1
  },
  ".local..0": {
    "description": "",
    "is_enabled": true,
    "is_up": true,
    "last_flapped": -1,
    "mac_address": "Unspecified",
    "mtu": 0,
    "speed": -1
  },
}
```

@pszulczewski FYI

**Comment by lvrfrc87** [comment]
I believe this could be a limitation from JMSPATH. The most similar case I found is this one:https://jmespath.org/tutorial.html#object-projections

As we can see, the our hypothetical reference key is lost using `*`.  I will drop a message on jmspath channel support but I feel that the user will have to do some post parsing using indexes

**Comment by lvrfrc87** [comment]
Looks like there is `keys(@)` which catches all dict keys. So in `jdiff` the path should be something like `keys(@).is_up` and should work. @pszulczewski FYI

![Screenshot 2022-11-15 at 10 25 43](https://user-images.githubusercontent.com/15066806/201882504-70055f7f-51fc-45ae-ae98-66055578ddc5.png)

**Comment by pszulczewski** [comment]
`keys(@)` produce list of keys, similar to python dict.keys(), they don't have access to values.

Thus `keys(@).is_up` or `$keys(@)$.is_up` return None.

**Comment by lvrfrc87** [comment]
At this point we have 3 options:

- Let the user use index to create a mapping between key and value got from `jdiff` - this will not work out of the box with pre defined checks
- Make `jdiff` dynamically discovery the data type and act accordingly - for this case the expression would be something like `$*$.is_up`
- Create some sort of flag

**Comment by lvrfrc87** [comment]
As discussed with @pszulczewski we will support `$*$.is_up` and interpolate the list of keys with the list of values returned.
