### ISSUE TITLE
Single value not supported  in expression 

### ISSUE THREAD

**Issue by lvrfrc87** [networktocode/jdiff#94]
In case an user wants to get extract just one element from the json object, he has to pass it in a list anyway

`"global.$peers$.*.is_enabled"` won't work
returns: `({'index_element[3]': {'new_value': False, 'old_value': True}}, False)`

`"global.$peers$.*.[is_enabled]"` will work 
returns: `({'7.7.7.7': {'is_enabled': {'new_value': False, 'old_value': True}}}, False)`

We can either fix or document as requirement

**Comment by chadell** [comment]
I would document

**Comment by pszulczewski** [comment]
Update.
After recent changes the proper key anchor is `"global.peers.$*$.is_enabled"`
It fails at: https://github.com/networktocode/jdiff/blob/7fbefb199e3476dd347bfb0e3c7a3726a2dfd860/jdiff/utils/jmespath_parsers.py#L91

Helper functions expect list-wrapped data.
`"global.peers.*.is_enabled"` returns `[True, True, False, True]`, while helpers expect `[[True], [True], [False], [True]]`
